# Generated by Django 2.1.2 on 2018-10-24 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aaulan', '0002_attendee_ticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat', models.CharField(max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Attendance',
            },
        ),
        migrations.CreateModel(
            name='CrewMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Crew member',
            },
        ),
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Prize',
            },
        ),
        migrations.CreateModel(
            name='TeamAssociation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_leader', models.BooleanField(verbose_name='Is team leader')),
            ],
            options={
                'verbose_name': 'Team association',
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('type', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Tournament',
            },
        ),
        migrations.RemoveField(
            model_name='attendee',
            name='teams',
        ),
        migrations.RemoveField(
            model_name='attendee',
            name='user',
        ),
        migrations.AlterField(
            model_name='team',
            name='leader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aaulan.Attendance'),
        ),
        migrations.DeleteModel(
            name='Attendee',
        ),
        migrations.AddField(
            model_name='teamassociation',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aaulan.Team'),
        ),
        migrations.AddField(
            model_name='teamassociation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aaulan.Attendance'),
        ),
        migrations.AddField(
            model_name='prize',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aaulan.Tournament'),
        ),
        migrations.AlterUniqueTogether(
            name='teamassociation',
            unique_together={('team', 'user')},
        ),
    ]
