# Generated by Django 2.1.2 on 2018-10-24 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aaulan', '0003_auto_20181024_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='leader',
        ),
    ]
