# Generated by Django 2.1.2 on 2018-10-27 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aaulan', '0005_auto_20181027_1119'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GameAdmin',
        ),
    ]
