# Generated by Django 2.1.2 on 2018-10-27 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aaulan', '0010_tournament_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='game',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='aaulan.Game'),
            preserve_default=False,
        ),
    ]
