# Generated by Django 2.1.2 on 2018-10-27 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aaulan', '0012_auto_20181027_1443'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prize',
            old_name='count',
            new_name='amount',
        ),
    ]
